// <auto-generated />
using Aotearoa_is_Home.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aotearoa_is_Home.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260829233329_SeedDataFix")]
    partial class SeedDataFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aotearoa_is_Home.Models.ContentBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("SettlementPageId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SettlementPageId");

                    b.ToTable("ContentBlocks");
                });

            modelBuilder.Entity("Aotearoa_is_Home.Models.SettlementInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SettlementInformation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Information regarding homestays, student accommodation, flatting, and tenant rights.",
                            Title = "Finding Accommodation",
                            Topic = "Accommodation"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Details about international student support, academic integrity, and university resources.",
                            Title = "Educational & Tertiary Information",
                            Topic = "Education"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Guidance on finding a GP, registering with a medical centre, and health insurance.",
                            Title = "Health Care and Wellbeing",
                            Topic = "Healthcare"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Everyday Kiwi words, slang, communication card prompts, and family language support.",
                            Title = "Language Support Resources",
                            Topic = "Language Assistance"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Information on work rights, CV/cover letter creation, interview etiquette, and workplace culture.",
                            Title = "Employment Rights & Job Hunting",
                            Topic = "Employment"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Opening a bank account, everyday transaction accounts, tracking weekly budgets, and IRD tax profiles.",
                            Title = "Banking & Financial Management",
                            Topic = "Banking & Finance"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Bus, train, and ferry logistics alongside NZ road rules, licensing setup, and vehicle ownership.",
                            Title = "Public Transport & Driving",
                            Topic = "Transport"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Making friends, university student clubs, local community centers, and cultural activities.",
                            Title = "Social Networks & Community",
                            Topic = "Community Support"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Daycare options, school zone applications, children's health checks, and local parenting culture.",
                            Title = "Childcare & School Enrolment",
                            Topic = "Childcare & Family"
                        },
                        new
                        {
                            Id = 10,
                            Description = "How to reach services via 111, dealing with natural disasters, and household safety guidelines.",
                            Title = "Emergency Support & Personal Safety",
                            Topic = "Emergency & Safety"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Details regarding student visa conditions, renewal steps, and staying compliant.",
                            Title = "Immigration & Visa Compliance",
                            Topic = "Immigration & Visa"
                        });
                });

            modelBuilder.Entity("Aotearoa_is_Home.Models.SettlementPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SettlementPages");
                });

            modelBuilder.Entity("Aotearoa_is_Home.Models.ContentBlock", b =>
                {
                    b.HasOne("Aotearoa_is_Home.Models.SettlementPage", "SettlementPage")
                        .WithMany("ContentBlocks")
                        .HasForeignKey("SettlementPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SettlementPage");
                });

            modelBuilder.Entity("Aotearoa_is_Home.Models.SettlementPage", b =>
                {
                    b.Navigation("ContentBlocks");
                });
#pragma warning restore 612, 618
        }
    }
}
